services:
  simulations:
    build:
      context: .
      dockerfile: Simulations.Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    command: python -m src.main_simulations
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - EXECUTION_ENV=local
  
  runs:
    build:
      context: .
      dockerfile: Runs.Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    command: python -m src.main_runs
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - EXECUTION_ENV=local

  model_training:
    build: .
    working_dir: /app
    command: python -m src.main_trainings
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - EXECUTION_ENV=local