services:
  simulation:
    build:
      context: .
      dockerfile: Simulation.Dockerfile
    user: "${UID}:${GID}"
    working_dir: /app
    command: python -m src.main_simulation
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - EXECUTION_ENV=local
  
  retrieve_runs:
    build: .
    user: "${UID}:${GID}"
    working_dir: /app
    command: python -m src.main_runs
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - EXECUTION_ENV=local

  model_training:
    build: .
    working_dir: /app
    command: python -m src.main_fitting
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - EXECUTION_ENV=local