name: Python CI/CD

on:
  push:
    branches:
      - '**' # runs on every branch push
  pull_request:
    branches:
      - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # specifies the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Linting check with ruff
        run: |
          ruff check .

  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust_sim -> rust_sim/target

      - name: Run unit tests
        run: cargo test --manifest-path [Cargo.toml](http://_vscodecontentref_/5) --all-targets

  python-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # specifies the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run unit tests
        working-directory: ./tests # where the test files are located
        env:
          PYTHONPATH: ${{ github.workspace }} # tells Python to see the whole repo
        run: |
          python test_unit.py